### ISSUE TITLE
Config file path

### ISSUE THREAD

**Issue by Ext3h** [translationexchange/tml-php#1]
The documentation hints that config/defaults.json should be copied to config/config.json, however the configuration never loads from config.json, as Tml\Config::configData has only defaults.json hardcoded.

A call to Tml\Config::configData however will dump the currently active configuration to config/config.json

**Comment by berk** [comment]
@Ext3h looks like an oversight in the documentation. I will update the docs. You really don't need the config file, unless you are planning to do a lot of customization. You can pass all your settings in the init itself. 

<?php tml_init(array(....)) ?>  

Probably a better way than messing around with JSON files.
