### ISSUE TITLE
LanguageSelectorJs.php not safe for XHTML

### ISSUE THREAD

**Issue by Ext3h** [translationexchange/tml-php#2]
The Javascript in LanguageSelectorJs.php should be properly encapsulated between `/* <![CDATA[ */` and `/* ]]> */` as the script tag is inserted somewhere in the body region, causing the content of the script tag being displayed as text when the document is parsed as XHTML.

**Comment by berk** [comment]
@Ext3h we are actually moving away from generating the language selectors in the PHP code. We now have 8 options for language selectors, but all of them are injected by the agent. This allows us to add more selectors without having to hardcode them in every SDK.

So you will notice that all of the selectors have been removed from the code here: 

https://github.com/translationexchange/tml-php/tree/master/src/Tml/Includes

**Comment by Ext3h** [comment]
Never mind then, I wasn't aware that 3.1.1 was published yet. It's no longer a problem then.
